"use client"
import Navbar from "./components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "./components/Footer";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import { Inter } from "next/font/google";
import { useState } from "react";
import Cart from "./components/Cart";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Makeup Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const [showCart, setShowCart] = useState(false)



  return (
    <html lang="en">
      <body
        className={inter.className}
      > <Provider store={store}>
         <Navbar setShowCart={setShowCart}/>
         {showCart && <Cart setShowCart={setShowCart} />}
        {children}
        <Footer/>
        </Provider> 
     
      </body>
    </html>
  );
}
